### ISSUE TITLE
Mobile screen broken although I have the tags put in.

### ISSUE THREAD

**Issue by seanokai** [seanokai/portfolio#7]
Good afternoon Thomas, I've been trying to find out the erro as to why my sigte is always showeign up broken on my mobile. I put it the viewport tags like usual but its coming up as an error on the validator site.
![screen shot 2015-10-26 at 3 23 56 pm](https://cloud.githubusercontent.com/assets/6353024/10740272/bfec3a28-7bf7-11e5-8857-d28a5ef35528.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
Those validation errors are perfectly okay, and can be ignored.

The error that's causing the site to not look right on mobile screens is in the HTML, this line here:
https://github.com/seanokai/portfolio/blob/gh-pages/_layouts/default.html#L11

It should be a comma separating the values, not a semi-colon, like this:

``` html
<meta name="viewport" content="width=device-width,initial-scale=1">
```
